version: "3.4"

services:
  backend:
    extends:
      file: ./docker-compose.base.yml
      service: backend
    links:
      - db
    env_file:
      - .env
    environment:
      DB_PASSWORD: no-password
      DB_USER: root
      DB_HOST: db
      PORT: 3100
    ports:
      - 9229:9229
      - 3100:3100
    command: yarn workspace @direbus/dailywatori-core run start -- --inspect=0.0.0.0:9229
    volumes:
      - "./.infra/storage:/usr/src/app/storage"

  db:
    extends:
      file: ./docker-compose.base.yml
      service: db
    environment:
      MYSQL_ROOT_PASSWORD: no-password
    volumes:
      - "./.infra/db:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: no-password
