version: "3.4"

services:
  backend:
    image: dally-dose
    build:
      context: .
    volumes:
      - "./:/usr/src/app"
    environment:
      PORT: 3100
    ports:
      - 3100:3100

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dailywatori
    volumes:
      - "./.infra/db:/var/lib/mysql"
